image: ubuntu:latest

stages:
  - deploy

before_script:
  - apt-get update && apt-get install -y openssh-client
variables:
#      GIT_STRATEGY: none
      PEMFILE: /tmp/your-key.pem
      IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$VERSION-QA
      SPRING_DATASOURCE_URL: ${DB_URL_QA} 
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME_QA} 
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD_QA} 
deploy_ec2:
  stage: deploy
  script:
    - echo "Decodificando la clave privada"
    - echo "$EC2_SSH_PRIVATE_KEY_BASE64" | base64 --decode > /tmp/your-key.pem
    - chmod 600 /tmp/your-key.pem
    - cat /tmp/your-key.pem
    - printenv
    - echo "Conectándose al servidor EC2" 
    - echo "Server Host-${EC2_IP_SERVERFRONT}"
    - ssh -o StrictHostKeyChecking=no -i /tmp/your-key.pem ${EC2_USER_AWS}@${EC2_IP_SERVERFRONT} 'echo "Conexión exitosa Server remoto-- ${EC2_IP_SERVERFRONT} \$SPRING_DATASOURCE_URL  -  \${DB_URL_QA}"'
    - ssh -o StrictHostKeyChecking=no -i /tmp/your-key.pem ${EC2_USER_AWS}@${EC2_IP_SERVERFRONT} 'docker ps'
